### ISSUE TITLE
Auto-scroll to newest element

### ISSUE THREAD

**Issue by ened** [gildaswise/firestore_ui#2]
Let’s add a feature to auto-scroll to latest/newest element once it’s inserted.

**Comment by ened** [comment]
Perhaps a easy solution by using the [ScrollController](https://docs.flutter.io/flutter/widgets/ScrollController-class.html) member.

**Comment by gildaswise** [comment]
Hey, I really would like to keep this library with basic features so it
doesn't get too hard to maintain; if you want to fork it and publish
another "feature-packed" firestore_ui based on this one, feel free to do it!

**Comment by gildaswise** [comment]
Did removing `setState` on `_onDocumentChanged` result in any unexpected behavior when receiving update data from Firestore? I had some issues with that when trying to reduce the setState usage but sadly didn't find another way around it.
