### ISSUE TITLE
How to get list length to identify end of stream?

### ISSUE THREAD

**Issue by amitash** [gildaswise/firestore_ui#25]
Is it possible to identify the last item in the list. Currently, I couldn't find a way to find the length of the list. This will be useful if I want to show a message when a user scrolls to the last item. Thank you.

**Comment by gildaswise** [comment]
With the `onLoaded` parameter you'll get the raw `QuerySnapshot` from each update, and from there you can access `.docs` to see the whole list. But that's just direct access to the data, it's not related to scrolling.

If you want it related to the scrolling itself, then I recommend this quick tutorial: https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac

**Comment by amitash** [comment]
Thanks. I can now get `docs.size` from `onLoaded`.
