### ISSUE TITLE
Flutter Version 3.7 breaking.. 'AnimatedGridState' is imported from both

### ISSUE THREAD

**Issue by adamfistival** [gildaswise/firestore_ui#36]
Flutter Version 3.7 breaking

: Error: 'AnimatedGridState' is imported from both 'package:firestore_ui/animated_grid.dart' and 'package:flutter/src/widgets/animated_scroll_view.dart'.
../…/lib/animated_firestore_grid.dart:7
import 'package:flutter/material.dart';
package:flutter/material.dart:1
^^^^^^^^^^^^^^^^^

: Error: 'AnimatedGrid' is imported from both 'package:firestore_ui/animated_grid.dart' and 'package:flutter/src/widgets/animated_scroll_view.dart'.
../…/lib/animated_firestore_grid.dart:302
    return AnimatedGrid(

**Comment by gildaswise** [comment]
For now you can just use `import 'package:flutter/material.dart' hide AnimatedGrid`, I'll fix this in an update later

**Comment by syonip** [comment]
Hi, I just had to fix this so my project would compile.
Created a PR #37 if you want to use it.
Cheers

**Comment by grosours** [comment]
hi @gildaswise 

> For now you can just use `import 'package:flutter/material.dart' hide AnimatedGrid`, I'll fix this in an update later

Hi I am also affected by the problem, do you mean to use this change inside the `firestore_ui` package?

I tried, it does indeed work but modifying a local copy of the package is a little hackish. I also tried to use this in my application but to no avail, which is what I would have expected.

**Comment by gildaswise** [comment]
@syonip @adamfistival @grosours I've just published 1.25.1 making my version of AnimatedGrid private, shouldn't have conflicts anymore.

**Comment by grosours** [comment]
@gildaswise work great 👍 ! thank you for the new release.
