### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by syonip** [gildaswise/firestore_ui#39]
Hi,
Getting this error with new firebase dependencies:

```
Because firebase_messaging >=14.7.0 depends on firebase_core_platform_interface ^5.0.0 and firestore_ui >=1.25.0 depends on firebase_core_platform_interface ^4.5.2, firebase_messaging >=14.7.0 is incompatible with firestore_ui >=1.25.0.
```
Thanks

**Comment by syonip** [comment]
For anyone that needs to use this with new flutter versions, I created a fork with updated dependencies:
https://github.com/syonip/firestore_ui/

You can use this in pubspec.yaml:

firestore_ui: 
    git: https://github.com/syonip/firestore_ui.git

**Comment by gildaswise** [comment]
Sorry about the delay here, I'm not really maintaining this anymore but I'll release 1.3.0 soon with the latest dependencies
