### ISSUE TITLE
Error with newest version of Cloud Firestore

### ISSUE THREAD

**Issue by rami-alloush** [gildaswise/firestore_ui#6]
The log is:
`E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getReference(CloudFirestorePlugin.java:93)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:194)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:614)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getReference(CloudFirestorePlugin.java:93)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:194)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:614)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4516): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 4516): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null)
E/flutter ( 4516): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 4516): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 4516): <asynchronous suspension>
E/flutter ( 4516): #2      Query.snapshots.<anonymous closure> (package:cloud_firestore/src/query.dart:56:37)
E/flutter ( 4516): #3      _runGuarded (dart:async/stream_controller.dart:805:24)
E/flutter ( 4516): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
E/flutter ( 4516): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
E/flutter ( 4516): #6      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
E/flutter ( 4516): #7      _FirestoreList&ListBase&StreamSubscriberMixin.listen (package:firestore_ui/stream_subscriber_mixin.dart:15:33)
E/flutter ( 4516): #8      new FirestoreList (package:firestore_ui/firestore_list.dart:33:5)
E/flutter ( 4516): #9      FirestoreAnimatedListState.didChangeDependencies (package:firestore_ui/animated_firestore_list.dart:163:14)
E/flutter ( 4516): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3958:12)
E/flutter ( 4516): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
E/flutter ( 4516): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
E/flutter ( 4516): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
E/flutter ( 4516): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
E/flutter ( 4516): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
E/flutter ( 4516): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5078:32)
E/flutter ( 4516): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
E/flutter ( 4516): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
E/flutter ( 4516): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
E/flutter ( 4516): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
E/flutter ( 4516): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
E/flutter ( 4516): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
E/flutter ( 4516): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
E/flutter ( 4516): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #41     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4159:11)
E/flutter ( 4516): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #43     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5078:32)
E/flutter ( 4516): #44  
E/flutter ( 4516): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null)
E/flutter ( 4516): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 4516): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 4516): <asynchronous suspension>
E/flutter ( 4516): #2      Query.snapshots.<anonymous closure> (package:cloud_firestore/src/query.dart:56:37)
E/flutter ( 4516): #3      _runGuarded (dart:async/stream_controller.dart:805:24)
E/flutter ( 4516): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
E/flutter ( 4516): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
E/flutter ( 4516): #6      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
E/flutter ( 4516): #7      _FirestoreList&ListBase&StreamSubscriberMixin.listen (package:firestore_ui/stream_subscriber_mixin.dart:15:33)
E/flutter ( 4516): #8      new FirestoreList (package:firestore_ui/firestore_list.dart:33:5)
E/flutter ( 4516): #9      FirestoreAnimatedListState.didChangeDependencies (package:firestore_ui/animated_firestore_list.dart:163:14)
E/flutter ( 4516): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3958:12)
E/flutter ( 4516): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
E/flutter ( 4516): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
E/flutter ( 4516): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
E/flutter ( 4516): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
E/flutter ( 4516): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
E/flutter ( 4516): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5078:32)
E/flutter ( 4516): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
E/flutter ( 4516): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
E/flutter ( 4516): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
E/flutter ( 4516): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
E/flutter ( 4516): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter ( 4516): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
E/flutter ( 4516): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
E/flutter ( 4516): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
E/flutter ( 4516): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter ( 4516): #41     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4159:11)
E/flutter ( 4516): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter ( 4516): #43     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5078:32)
E/flutter ( 4516): #44  
`

My versions are:
`  firebase_core: ^0.4.0+6
  firebase_analytics: ^3.0.3
  firebase_auth: ^0.11.1+7
  firestore_ui: ^1.6.0
  cloud_firestore: ^0.12.5+2`

**Comment by gildaswise** [comment]
Hey, rami! Could you send a snippet of code, or a gist, to reproduce this? Seems like this was a conflict where you changed the variable type on the database but not on the app.
