### ISSUE TITLE
Animate remaining list items after item removed

### ISSUE THREAD

**Issue by opringle** [gildaswise/firestore_ui#9]
I implemented an AnimatedFirestoreList as per the documentation. When an item is removed, it animates out correctly. However, the remaining list items instantaneously jump into the new available space. I would expect them to smoothly slide into the space, like with AnimatedList.

Is this behaviour as expected?

**Comment by opringle** [comment]
The solution was to use a SizeTransition to reduce the card height.

**Comment by gildaswise** [comment]
Yeah, that's just the default behaviour for FadeTransition! Glad that you got it to work with SizeTransition!
